chore: fix types for pa11y
Financial-Times/dotcom-tool-kit pull request #239
Opened 2022-05-17 14:27 UTC by apaleslimghost

2022-05-17 16:18 UTC, serena97 approved these changes

2022-05-17 16:19 UTC, serena97 requested changes
file changes look good, but we should change this commit message to fix

2022-05-24 11:09 UTC, apaleslimghost commented
it's not really `fix` since the incorrect types weren't ever in any actually-released version, just the rebased `main`

2022-05-24 11:11 UTC, serena97 approved these changes

2022-05-24 11:11 UTC, merged