Allow Pa11y to use config defined in .pa11yci
Financial-Times/dotcom-tool-kit pull request #258
Opened 2022-06-27 17:06 UTC by ivomurrell

Instead of passing static options to Pa11y, calling the `pa11y-ci` binary instead reads config defined in a `.pa11yci[.js[on]]` file. Seeing as this can be a `.js` file, the config can be dynamically generated, making the tooling much more flexible. This was how n-gage interfaced with Pa11y.

This also solves an issue that reported validation errors from Pa11y as internal errors within Pa11y.

2022-07-21 10:05 UTC, joelcarr commented
Looks good to me, just need to update this branch with `main` 🙌

2022-07-21 15:57 UTC, joelcarr approved these changes

2022-07-27 10:15 UTC, joelcarr requested changes
**issue:** This looks like it should be a breaking change commit as we are changing how to set the config.

2022-07-27 10:37 UTC, ivomurrell commented
Good point: I initially thought it would be okay doing a minor update as those are treated as breaking changes in prerelease versions (`< 1.0.0`) but actually this change would have been released as a patch update because we have [`bump-minor-pre-major`](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#configfile) enabled in our release-please config.

2022-07-27 11:04 UTC, joelcarr approved these changes
Brilliant!

2022-07-27 11:06 UTC, merged