change nested stack template to v2
Financial-Times/dotcom-tool-kit pull request #657
Opened 2024-05-24 15:17 UTC by hamza-samih

# Description

We've changed the permissions in our OIDC nested stack role, in order to remove legacy role assumptions by the old ft-engineer and ft-iam-admin roles. This PR updates to the latest template (v2).

The v2 template has slightly differing permissions, but should affect apps role assumptions, and there should be no effect on deployments.

PR for template changes here: https://github.com/Financial-Times/circleci-nested-stack-template/pull/25

2024-05-24 15:34 UTC, apaleslimghost requested changes
hi Hamza, thanks for the PR! we use [release-please](https://github.com/googleapis/release-please) and [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/), so for this to be releasable you'll need to prefix the commit message with `feat:`

2024-05-24 15:37 UTC, apaleslimghost commented
also please note that this template is only used when setting up new repos with Tool Kit, we'll also need to update existing repos, will you be working on that?

2024-05-28 12:29 UTC, hamza-samih commented
Thanks @apaleslimghost i've amended the commit message to comply with release-please. R.e updating existing repo's, we've done this already in nearly all aws-composer accounts, but I can't find too many instances outside of them. A q[uick Github search ](https://github.com/search?q=org%3AFinancial-Times+https%3A%2F%2Fcircleci-nested-stack-template-bucket.s3.eu-west-1.amazonaws.com%2Fcircleci-nested-stack-role.yaml&type=code)shows that there's not many occurrences left.

2024-05-28 12:29 UTC, apaleslimghost approved these changes

2024-05-28 12:30 UTC, merged

2024-05-28 12:30 UTC, apaleslimghost commented
thanks @hamza-samih!